# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f9f627ddc4e4e7f74ee5fa4ae1566ce26fc148a1c3071fd685d7ce8708f2495e3561630310606d379fa9303805662aded98e2966fdaac017788dd43b86cf9e68

test:
  secret_key_base: 1c190bb29df823b52e7664293de286919db924b80527b47e7fbc2cce3790336cbf5eb2105f2064a093126e0f8933f4648c89ef42439b30bb31dc95957b054a34

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
